services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        NODE_VERSION: 20
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CI=true
      - HUSKY=0
      - NODE_OPTIONS=--max-old-space-size=4096
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  node_modules:
