version: "3.8"

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        NODE_VERSION: 20
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CI=true
      - HUSKY=0

volumes:
  node_modules:
